wandb_version: 1

config:
  desc: null
  value: config/config.yaml
seed:
  desc: null
  value: 42
savepath:
  desc: null
  value: blip_reward
batch_size:
  desc: null
  value: 4
gradient_accumulation_steps:
  desc: null
  value: 4
epochs:
  desc: null
  value: 10
train_iters:
  desc: null
  value: 57480
distributed:
  desc: null
  value: true
gpu_num:
  desc: null
  value: 4
gpu_id:
  desc: null
  value: 2,3,4,5
load_emb:
  desc: null
  value: false
load_pair_store:
  desc: null
  value: false
fix_base:
  desc: null
  value: false
fix_rate:
  desc: null
  value: 0.7
lr:
  desc: null
  value: 1.0e-05
lr_decay_iters:
  desc: null
  value: null
lr_decay_style:
  desc: null
  value: cosine
lr_decay_ratio:
  desc: null
  value: 0.0
warmup:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_eps:
  desc: null
  value: 1.0e-08
clear_visualizer:
  desc: null
  value: true
output_dir:
  desc: null
  value: /data/liutao/checkpoints/blipreward
valid_per_epoch:
  desc: null
  value: 4
test_ckpt:
  desc: null
  value: null
BatchSize:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706095127.004211
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.27.4
      8:
      - 5
      13: linux-x86_64
